// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akkqglgzruerwcamkmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFra3FnbGd6cnVlcndjYW1rbWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODg2NTQsImV4cCI6MjA2NDU2NDY1NH0.75rM4mhD7G63ZDK-zB8r3guL1creXH2oyHtmQ8MqDXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);